export const LOAD_NEW_STAKEHOLDER = 'LOAD_NEW_STAKEHOLDER';
export const UPDATE_STAKEHOLDER_FIELD = 'UPDATE_STAKEHOLDER_FIELD';

export const STAKEHOLDER_LIST_REQUEST = 'STAKEHOLDER_LIST_REQUEST';
export const STAKEHOLDER_LIST_SUCCESS = 'STAKEHOLDER_LIST_SUCCESS';
export const STAKEHOLDER_LIST_ERROR = 'STAKEHOLDER_LIST_ERROR';

export const STAKEHOLDER_LOAD_REQUEST = 'STAKEHOLDER_LOAD_REQUEST';
export const STAKEHOLDER_LOAD_SUCCESS = 'STAKEHOLDER_LOAD_SUCCESS';
export const STAKEHOLDER_LOAD_ERROR = 'STAKEHOLDER_LOAD_ERROR';

export const STAKEHOLDER_SAVE_REQUEST = 'STAKEHOLDER_SAVE_REQUEST';
export const STAKEHOLDER_SAVE_SUCCESS = 'STAKEHOLDER_SAVE_SUCCESS';
export const STAKEHOLDER_SAVE_ERROR = 'STAKEHOLDER_SAVE_ERROR';

export const STAKEHOLDER_DELETE_REQUEST = 'STAKEHOLDER_DELETE_REQUEST';
export const STAKEHOLDER_DELETE_SUCCESS = 'STAKEHOLDER_DELETE_SUCCESS';
export const STAKEHOLDER_DELETE_ERROR = 'STAKEHOLDER_DELETE_ERROR';
