export const LOAD_NEW_REVIEW = 'LOAD_NEW_REVIEW';
export const UPDATE_REVIEW_FIELD = 'UPDATE_REVIEW_FIELD';

export const REVIEW_REPLY_REQUEST = 'REVIEW_REPLY_REQUEST';
export const REVIEW_REPLY_SUCCESS = 'REVIEW_REPLY_SUCCESS';
export const REVIEW_REPLY_ERROR = 'REVIEW_REPLY_ERROR';

export const REVIEW_LIST_REQUEST = 'REVIEW_LIST_REQUEST';
export const REVIEW_LIST_SUCCESS = 'REVIEW_LIST_SUCCESS';
export const REVIEW_LIST_ERROR = 'REVIEW_LIST_ERROR';

export const REVIEW_LOAD_REQUEST = 'REVIEW_LOAD_REQUEST';
export const REVIEW_LOAD_SUCCESS = 'REVIEW_LOAD_SUCCESS';
export const REVIEW_LOAD_ERROR = 'REVIEW_LOAD_ERROR';

export const REVIEW_SAVE_REQUEST = 'REVIEW_SAVE_REQUEST';
export const REVIEW_SAVE_SUCCESS = 'REVIEW_SAVE_SUCCESS';
export const REVIEW_SAVE_ERROR = 'REVIEW_SAVE_ERROR';

export const REVIEW_DELETE_REQUEST = 'REVIEW_DELETE_REQUEST';
export const REVIEW_DELETE_SUCCESS = 'REVIEW_DELETE_SUCCESS';
export const REVIEW_DELETE_ERROR = 'REVIEW_DELETE_ERROR';

export const PENDING_REVIEW_REQUEST = 'PENDING_REVIEW_REQUEST';
export const PENDING_REVIEW_SUCCESS = 'PENDING_REVIEW_SUCCESS';
export const PENDING_REVIEW_ERROR = 'PENDING_REVIEW_ERROR';
