export const PROFILE_LOAD_REQUEST = 'PROFILE_LOAD_REQUEST';
export const PROFILE_LOAD_SUCCESS = 'PROFILE_LOAD_SUCCESS';
export const PROFILE_LOAD_ERROR = 'PROFILE_LOAD_ERROR';

export const PROFILE_SAVE_REQUEST = 'PROFILE_SAVE_REQUEST';
export const PROFILE_SAVE_SUCCESS = 'PROFILE_SAVE_SUCCESS';
export const PROFILE_SAVE_ERROR = 'PROFILE_SAVE_ERROR';

export const PROFILE_DELETE_REQUEST = 'PROFILE_DELETE_REQUEST';
export const PROFILE_DELETE_SUCCESS = 'PROFILE_DELETE_SUCCESS';
export const PROFILE_DELETE_ERROR = 'PROFILE_DELETE_ERROR';

export const LOAD_NEW_USER = 'LOAD_NEW_USER';
export const UPDATE_PROFILE_FIELD = 'UPDATE_PROFILE_FIELD';
