export const LOAD_NEW_RESTAURANT = 'LOAD_NEW_RESTAURANT';
export const UPDATE_RESTAURANT_FIELD = 'UPDATE_RESTAURANT_FIELD';

export const RESTAURANT_LIST_REQUEST = 'RESTAURANT_LIST_REQUEST';
export const RESTAURANT_LIST_SUCCESS = 'RESTAURANT_LIST_SUCCESS';
export const RESTAURANT_LIST_ERROR = 'RESTAURANT_LIST_ERROR';

export const RESTAURANT_LOAD_REQUEST = 'RESTAURANT_LOAD_REQUEST';
export const RESTAURANT_LOAD_SUCCESS = 'RESTAURANT_LOAD_SUCCESS';
export const RESTAURANT_LOAD_ERROR = 'RESTAURANT_LOAD_ERROR';

export const RESTAURANT_SAVE_REQUEST = 'RESTAURANT_SAVE_REQUEST';
export const RESTAURANT_SAVE_SUCCESS = 'RESTAURANT_SAVE_SUCCESS';
export const RESTAURANT_SAVE_ERROR = 'RESTAURANT_SAVE_ERROR';

export const RESTAURANT_DELETE_REQUEST = 'RESTAURANT_DELETE_REQUEST';
export const RESTAURANT_DELETE_SUCCESS = 'RESTAURANT_DELETE_SUCCESS';
export const RESTAURANT_DELETE_ERROR = 'RESTAURANT_DELETE_ERROR';
