export const LOAD_NEW_CONNECTION = 'LOAD_NEW_CONNECTION';
export const UPDATE_CONNECTION_FIELD = 'UPDATE_CONNECTION_FIELD';

export const CONNECTION_LIST_REQUEST = 'CONNECTION_LIST_REQUEST';
export const CONNECTION_LIST_SUCCESS = 'CONNECTION_LIST_SUCCESS';
export const CONNECTION_LIST_ERROR = 'CONNECTION_LIST_ERROR';

export const CONNECTION_LOAD_REQUEST = 'CONNECTION_LOAD_REQUEST';
export const CONNECTION_LOAD_SUCCESS = 'CONNECTION_LOAD_SUCCESS';
export const CONNECTION_LOAD_ERROR = 'CONNECTION_LOAD_ERROR';

export const CONNECTION_SAVE_REQUEST = 'CONNECTION_SAVE_REQUEST';
export const CONNECTION_SAVE_SUCCESS = 'CONNECTION_SAVE_SUCCESS';
export const CONNECTION_SAVE_ERROR = 'CONNECTION_SAVE_ERROR';

export const CONNECTION_DELETE_REQUEST = 'CONNECTION_DELETE_REQUEST';
export const CONNECTION_DELETE_SUCCESS = 'CONNECTION_DELETE_SUCCESS';
export const CONNECTION_DELETE_ERROR = 'CONNECTION_DELETE_ERROR';

export const CONNECTION_EXPORT_REQUEST = 'CONNECTION_EXPORT_REQUEST';
export const CONNECTION_EXPORT_SUCCESS = 'CONNECTION_EXPORT_SUCCESS';
export const CONNECTION_EXPORT_ERROR = 'CONNECTION_EXPORT_ERROR';

export const CONNECTION_RELATED_STAKEHOLDER_DELETE_SUCCESS = 'CONNECTION_RELATED_STAKEHOLDER_DELETE_SUCCESS';
