export const LOAD_NEW_PROJECT = 'LOAD_NEW_PROJECT';
export const UPDATE_PROJECT_FIELD = 'UPDATE_PROJECT_FIELD';

export const PROJECT_LIST_REQUEST = 'PROJECT_LIST_REQUEST';
export const PROJECT_LIST_SUCCESS = 'PROJECT_LIST_SUCCESS';
export const PROJECT_LIST_ERROR = 'PROJECT_LIST_ERROR';

export const PROJECT_LOAD_REQUEST = 'PROJECT_LOAD_REQUEST';
export const PROJECT_LOAD_SUCCESS = 'PROJECT_LOAD_SUCCESS';
export const PROJECT_LOAD_ERROR = 'PROJECT_LOAD_ERROR';

export const PROJECT_SAVE_REQUEST = 'PROJECT_SAVE_REQUEST';
export const PROJECT_SAVE_SUCCESS = 'PROJECT_SAVE_SUCCESS';
export const PROJECT_SAVE_ERROR = 'PROJECT_SAVE_ERROR';

export const PROJECT_DELETE_REQUEST = 'PROJECT_DELETE_REQUEST';
export const PROJECT_DELETE_SUCCESS = 'PROJECT_DELETE_SUCCESS';
export const PROJECT_DELETE_ERROR = 'PROJECT_DELETE_ERROR';
